### ISSUE TITLE
how to use it in Gradle ?

### ISSUE THREAD

**Issue by AngleV** [OCman/SearchViewWidget#1]

**Comment by OCman** [comment]
I am working to add a dependency to Gradle right now :). Check Readme in hour.

**Comment by AngleV** [comment]
Cool !

**Comment by AngleV** [comment]
Readme file never updated :D

**Comment by OCman** [comment]
I thought you will say it :D. I have some issues with uploading. Dependency will be probably tomorrow.

**Comment by AngleV** [comment]
:D
ok mate thank you !

**Comment by OCman** [comment]
Dependency is uploaded to jCenter. It will be in README on GitHub very soon.﻿
